### ISSUE TITLE
White paper

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx-simulator#1]
Create a white-paper document:
 - [x] abstract
 - [x] statement
 - [x] function requirements
 - [x] non-functional requirements
 - [x] solution

@IlyaMoskva let me know if some sections are missed.

**Comment by g4s8** [comment]
@IlyaMoskva please pay attention, we still need to describe non-functional requirements

**Comment by IlyaMoskva** [comment]
@g4s8 , As PR #9 merged, may we set non-functional reqs bullet checked now and close this ticket?

**Comment by g4s8** [comment]
@IlyaMoskva sure, thanks
